name: CIlung

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: cok
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        uut: [1, 2]
        pante: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: lscpu
